"""Scrub / enum-preservation policy used by schema engines."""

from .fields import (
    BLOCKED_VALUE_FIELD_PREFIXES,
    BLOCKED_VALUE_FIELD_SUFFIXES,
    BLOCKED_VALUE_FIELDS_EXACT,
    MAX_ENUM_VALUES,
    MAX_PRESERVE_LEN,
    NAME_KEY_ALLOW,
    SENSITIVE_SHAPES,
)

__all__ = [
    "BLOCKED_VALUE_FIELDS_EXACT",
    "BLOCKED_VALUE_FIELD_PREFIXES",
    "BLOCKED_VALUE_FIELD_SUFFIXES",
    "MAX_ENUM_VALUES",
    "MAX_PRESERVE_LEN",
    "NAME_KEY_ALLOW",
    "SENSITIVE_SHAPES",
]
