# Generated by Django 5.2.17 on 2026-09-26 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("annotations", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("approved", models.BooleanField(default=False, help_text="Approved by an admin.")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ActorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("approved", models.BooleanField(default=False, help_text="Approved by an admin.")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MetadataRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("approved", models.BooleanField(default=False, help_text="Approved by an admin.")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ObjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("approved", models.BooleanField(default=False, help_text="Approved by an admin.")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Representation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        choices=[
                            ("activity", "Something happened"),
                            ("object", "Something exists"),
                            ("unmapped", "No confident semantic mapping"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="representations",
                        to="representations.activitytype",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="as_actor",
                        to="representations.actortype",
                    ),
                ),
                (
                    "annotations",
                    models.ManyToManyField(
                        blank=True, related_name="representations", to="annotations.annotation"
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="as_object",
                        to="representations.objecttype",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        help_text="Indirect object, e.g. the collection a video is added to.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="as_target",
                        to="representations.objecttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RepresentationMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("actor", "The actor (who did it)"),
                            ("activity", "The activity itself (when, how long)"),
                            ("object", "The object (what it was done to, or what exists)"),
                            ("target", "The target (the indirect object)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_links",
                        to="annotations.annotation",
                    ),
                ),
                (
                    "representation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_links",
                        to="representations.representation",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="representations.metadatarole",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="representation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("activity__isnull", False),
                        ("actor__isnull", False),
                        ("object__isnull", False),
                        ("pattern", "activity"),
                    ),
                    models.Q(
                        ("activity__isnull", True),
                        ("actor__isnull", True),
                        ("object__isnull", False),
                        ("pattern", "object"),
                        ("target__isnull", True),
                    ),
                    models.Q(
                        ("activity__isnull", True),
                        ("actor__isnull", True),
                        ("object__isnull", True),
                        ("pattern", "unmapped"),
                        ("target__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="representation_fields_match_pattern",
            ),
        ),
        migrations.AddConstraint(
            model_name="representationmetadata",
            constraint=models.UniqueConstraint(
                fields=("representation", "annotation", "role", "subject"),
                name="unique_representation_metadata_link",
            ),
        ),
    ]
