# Generated by Django 5.2.17 on 2026-09-26 13:42

from django.db import migrations

# {slug: (name, description)}; curators extend them in the admin.
SEEDS = {
    "ActorType": {
        "user": ("user", "The user whose behaviour is depicted in the data (data donor)"),
        "platform": ("platform", "The platform"),
        "other-user": (
            "other user",
            "Another account on the platform, e.g. a follower or commenter.",
        ),
    },
    "ActivityType": {
        "view": ("view", "The actor has viewed the object."),
        "open": ("open", "The actor opened the object, e.g. an app or a link."),
        "listen": ("listen", "The actor has listened to the object."),
        "create": ("create", "The actor has created the object."),
        "follow": ("follow", "The actor is following the object, e.g. an account."),
        "block": ("block", "The actor is blocking the object."),
        "join": ("join", "The actor has joined the object, e.g. a group or live."),
        "update": ("update", "The actor has changed the object."),
        "question": ("question", "The actor asked a question, e.g. a poll."),
        "add": ("add", "The actor has added the object to the target."),
    },
    "ObjectType": {
        "note": ("note", "A short text, e.g. a comment or a message."),
        "video": ("video", "A video."),
        "audio": ("audio", "An audio recording, e.g. a song or podcast."),
        "image": ("image", "An image, e.g. a photo."),
        "profile": ("profile", "What describes an account: name, bio, settings."),
        "person": ("person", "An individual person, e.g. an account holder."),
        "collection": ("collection", "A set of items, e.g. a playlist."),
        "event": ("event", "Something taking place at a time, e.g. a live stream."),
        "object": ("object", "Anything no more specific type fits."),
    },
    "MetadataRole": {
        "when": ("when", "When it happened or was created."),
        "context": ("context", "The setting it happened in, e.g. app surface or device."),
        "duration": ("duration", "How long it lasted."),
        "name": ("name", "A human-readable name or title."),
        "identifier": ("identifier", "What identifies it, e.g. an ID or a URL."),
        "author": ("author", "Who created it."),
        "value": ("value", "Its content or a measured value, e.g. a comment's text or a count."),
        "applies-to": ("applies to", "What it refers to, e.g. the post a comment replies to."),
    },
}


def seed(apps, schema_editor):
    for model_name, terms in SEEDS.items():
        model = apps.get_model("representations", model_name)
        for slug, (name, description) in terms.items():
            model.objects.get_or_create(
                slug=slug, defaults={"name": name, "description": description, "approved": True}
            )


def unseed(apps, schema_editor):
    for model_name, terms in SEEDS.items():
        model = apps.get_model("representations", model_name)
        model.objects.filter(slug__in=terms, created_by=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("representations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
