# Generated by Django 5.2.17 on 2026-09-29 15:17
"""Representations move from annotations to locations (0005): the old ones, their metadata links
and the suggestions about them are discarded, not converted."""

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

# the representation kinds of proposals before this change
OLD_KINDS = (
    "new_representation",
    "edit_representation",
    "represent",
    "describe",
    "unrepresent",
    "undescribe",
)


def discard(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    apps.get_model("proposals", "Proposal").objects.filter(kind__in=OLD_KINDS).delete()
    apps.get_model("representations", "RepresentationMetadata").objects.all().delete()
    apps.get_model("representations", "Representation").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("representations", "0003_rename_activity_terms"),
        ("proposals", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(discard, migrations.RunPython.noop),
    ]
