# Generated by Django 5.2.17 on 2026-09-29 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representations', '0004_discard_representations'),
        ('schemas', '0002_example_sources'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='representationmetadata',
            name='unique_representation_metadata_link',
        ),
        migrations.RemoveField(
            model_name='representation',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='representationmetadata',
            name='annotation',
        ),
        migrations.AddField(
            model_name='representation',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='schemas.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='representationmetadata',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_links', to='schemas.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='representation',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='representationmetadata',
            constraint=models.UniqueConstraint(fields=('representation', 'location', 'role', 'subject'), name='unique_representation_metadata_link'),
        ),
    ]
