# Generated by Django 5.2.17 on 2026-09-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("annotations", "0001_initial"),
        ("ddps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.TextField()),
                ("parent_path", models.TextField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("name", models.TextField(blank=True, null=True)),
                ("ignored", models.BooleanField(default=False, help_text="Not a data point.")),
                (
                    "example_values",
                    models.JSONField(
                        blank=True, default=list, help_text="Curated, non-personal example values."
                    ),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="annotations.annotation",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="ddps.platform",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("is_data_point", models.BooleanField(default=False)),
                ("type", models.CharField(blank=True, max_length=100)),
                ("shape", models.CharField(blank=True, max_length=32)),
                ("format", models.CharField(blank=True, max_length=100)),
                ("details", models.JSONField(default=dict)),
                ("suggestions", models.JSONField(default=list)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="schemas.location",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="ddps.upload",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["platform", "parent_path"], name="location_children"),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("platform", "path"), name="unique_location_path"
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["location", "upload"], name="observation_location"),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.UniqueConstraint(
                fields=("upload", "location"), name="unique_observation"
            ),
        ),
    ]
