# Generated by Django 5.2.17 on 2026-09-27 12:33

from django.db import migrations


def with_sources(apps, schema_editor):
    """Examples typed before sources existed: ``"Jane"`` → ``{"value": "Jane", "source":
    "user_input"}`` (schemas/examples.py)."""
    Location = apps.get_model("schemas", "Location")
    for location in Location.objects.exclude(example_values=[]):
        location.example_values = [
            value if isinstance(value, dict) else {"value": value, "source": "user_input"}
            for value in location.example_values
        ]
        location.save(update_fields=["example_values"])


def without_sources(apps, schema_editor):
    Location = apps.get_model("schemas", "Location")
    for location in Location.objects.exclude(example_values=[]):
        location.example_values = [
            value["value"] if isinstance(value, dict) else value
            for value in location.example_values
        ]
        location.save(update_fields=["example_values"])


class Migration(migrations.Migration):
    dependencies = [
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(with_sources, without_sources),
    ]
