# Generated by Django 5.2.17 on 2026-09-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("annotations", "0001_initial"),
        ("ddps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="ddps.platform",
            ),
        ),
    ]
