# Generated by Django 5.2.17 on 2026-09-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='pii',
            field=models.BooleanField(default=False, help_text='Relates to personally identifiable information.', verbose_name='PII'),
        ),
    ]
