#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# live preview of docs/ (mounted at /docs); rebuilds on every change
exec mkdocs serve --config-file /docs/mkdocs.yml --dev-addr 0.0.0.0:9000
