# Generated by Django 5.2.17 on 2026-09-25 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ddps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(
                fields=["platform", "requested_at"], name="upload_platform_requested"
            ),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(fields=["language"], name="upload_language"),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(fields=["root_format"], name="upload_root_format"),
        ),
    ]
