# Generated by Django 5.2.17 on 2026-09-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddps", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="request_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DL_APP", "Downloaded in the app"),
                    ("DL_BROWSER", "Downloaded in the browser"),
                    ("PAPI", "Downloaded through the Portability API"),
                ],
                help_text="How the DDP was requested, if known.",
                max_length=64,
            ),
        ),
    ]
