# Generated by Django 5.2.17 on 2026-09-26 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddps", "0003_upload_request_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="file_format",
            field=models.CharField(
                blank=True,
                choices=[("zip", "ZIP archive"), ("json", "JSON file"), ("csv", "CSV file")],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="plausibility",
            field=models.CharField(
                choices=[
                    ("pending", "Not checked yet"),
                    ("passed", "Counts"),
                    ("unconfirmed", "Unusual: to be confirmed by the uploader"),
                    ("awaiting", "Waiting for approval"),
                    ("approved", "Counts (approved)"),
                    ("rejected", "Rejected"),
                    ("duplicate", "Duplicate"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="plausibility_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first", "The first upload of its platform and format"),
                    ("dissimilar", "Unlike the other uploads of its platform and format"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="similarity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
