# Generated by Django 5.2.17 on 2026-09-26 19:23

from django.db import migrations


def passed(apps, schema_editor):
    """Uploads registered before the plausibility checks existed count as passed."""
    Upload = apps.get_model("ddps", "Upload")
    Upload.objects.filter(registered_at__isnull=False).update(plausibility="passed")


class Migration(migrations.Migration):
    dependencies = [
        ("ddps", "0004_upload_plausibility"),
    ]

    operations = [
        migrations.RunPython(passed, migrations.RunPython.noop),
    ]
