# Generated by Django 5.2.17 on 2026-09-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddps", "0005_registered_uploads_passed"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sealed", models.BinaryField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="own_values",
                        to="ddps.upload",
                    ),
                ),
            ],
        ),
    ]
