# Generated by Django 5.2.17 on 2026-09-28 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddps', '0007_anonymize_file_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='request_format',
            field=models.CharField(blank=True, choices=[('zip', 'ZIP archive'), ('json', 'JSON file'), ('csv', 'CSV file')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['request_format'], name='upload_request_format'),
        ),
    ]
