# Generated by Django 5.2.17 on 2026-09-28 18:20

import ddp_tracker.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddps', '0008_upload_request_format_upload_upload_request_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='document',
            field=ddp_tracker.core.fields.OrderedJSONField(blank=True, null=True),
        ),
    ]
