# Generated by Django 5.2.17 on 2026-09-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddps', '0009_upload_document_ordered_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='request_format',
            field=models.CharField(blank=True, choices=[('json', 'JSON'), ('csv', 'CSV')], max_length=64),
        ),
    ]
