# Generated by Django 5.2.17 on 2026-09-30 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddps', '0010_request_format_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('variable_key', 'Variable key: rename matching keys'), ('keep_key', 'Keep key: never rename matching keys')], default='variable_key', max_length=16)),
                ('pattern', models.TextField(help_text='A key path as the tracker shows it; * matches any one segment, and in the last segment (the key) becomes {*}: /user_data_tiktok.json/Direct Message/Direct Messages/ChatHistory/Chat History with *')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_rules', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_rules', to='ddps.platform')),
            ],
            options={
                'ordering': ['platform', 'kind', 'pattern'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'kind', 'pattern'), name='unique_path_rule')],
            },
        ),
    ]
