# Generated by Django 5.2.17 on 2026-09-27 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0003_initial'),
        ('ddps', '0006_upload_values'),
        ('representations', '0002_seed_vocabularies'),
        ('schemas', '0002_example_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('link', 'Link to an annotation'), ('new_annotation', 'New annotation'), ('ignore', 'Not a data point'), ('unassign', 'Remove the assignment'), ('edit_annotation', 'Edit the annotation'), ('new_representation', 'New representation'), ('edit_representation', 'Edit the representation'), ('represent', "Link as the representation's entity"), ('describe', "Link as the representation's metadata"), ('unrepresent', 'Remove the entity link'), ('undescribe', 'Remove the metadata link')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('superseded', 'Superseded')], default='open', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='Why (from the proposer).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Why it was rejected or superseded.')),
                ('subject', models.CharField(blank=True, choices=[('actor', 'The actor (who did it)'), ('activity', 'The activity itself (when, how long)'), ('object', 'The object (what it was done to, or what exists)'), ('target', 'The target (the indirect object)')], max_length=20)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('base', models.JSONField(blank=True, default=dict)),
                ('annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='annotations.annotation')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_proposals', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='schemas.location')),
                ('metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='representations.representationmetadata')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='ddps.platform')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('representation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='representations.representation')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='representations.metadatarole')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'kind'], name='proposal_status_kind')],
            },
        ),
    ]
