# Generated by Django 5.2.17 on 2026-09-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='role',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='subject',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='kind',
            field=models.CharField(choices=[('link', 'Link to an annotation'), ('new_annotation', 'New annotation'), ('ignore', 'Not a data point'), ('unassign', 'Remove the assignment'), ('edit_annotation', 'Edit the annotation'), ('new_representation', 'New representation'), ('edit_representation', 'Edit the representation'), ('delete_representation', 'Delete the representation')], max_length=32),
        ),
    ]
